# configs/train_config.yaml

seed: 42

data:
  dataset_path: "data/PlantVillage"
  image_size: [224, 224]
  batch_size: 512
  val_split: 0.2
  num_classes: 15

training:
  epochs: 100
  optimizer: AdamW
  learning_rate: 0.0003
  weight_decay: 1e-4
  scheduler: cosine_annealing
  warm_restarts: true
  early_stopping_patience: 10
  checkpoint_dir: "outputs/checkpoints"
  log_dir: "outputs/logs"

callbacks:
  model_checkpoint: true
  reduce_lr_on_plateau: true
  tensorboard: true
  early_stopping: true

explainability:
  grad_cam_layers: ["conv5_block3_out"]
  lime_samples: 1000
  tsne_perplexity: 30
